version: 0.0

os: linux

files:
    - source: /
      destination: /home/ubuntu/app

file_exists_behavior: OVERWRITE

hooks:
    ValidateService:
        - location: scripts/after-install.sh
          runas: ubuntu
