version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 20.x
    build:
        commands:
            - npm install
            - npm run build

cache:
    paths:
        - node_modules/**/*

artifacts:
    files:
        - node_modules/**/*
        - appspec.yml
        - scripts/**/*
        - dist/**/*
        - message.txt
